### ISSUE TITLE
feature request: report code coverage statistics to teamcity

### ISSUE THREAD

**Issue by antoniosZ** [eratio08/vitest-teamcity-reporter#204]
Hello,

Please add the appropriate [Build Statistics](https://www.jetbrains.com/help/teamcity/service-messages.html#Reporting+Build+Statistics) messages, in order to report to TeamCity the Code Coverage Statistics, so that TeamCity can then use in Charts/Reports/Failure Conditions/etc.

References:
1. https://www.jetbrains.com/help/teamcity/importing-arbitrary-coverage-results-to-teamcity.html
2. https://www.jetbrains.com/help/teamcity/service-messages.html#Reporting+Build+Statistics
3. https://www.jetbrains.com/help/teamcity/custom-chart.html#Default+Statistics+Values+Provided+by+TeamCity

Similar TeamCity reporter (for Jest though) that has this feature:
https://github.com/winterbe/jest-teamcity-reporter/blob/ffc6f38c8161d501b39a56fb513826c35761c91e/index.js#L62

Thank you.

**Comment by a3mitskevich** [comment]
@antoniosZ Hi. Vitest provides teamcity coverage reporter out of the box
![image](https://github.com/eratio08/vitest-teamcity-reporter/assets/77048647/33351502-8d81-446b-a561-26256d42776a)
They don't write about it in doc because it is an external library that they provide in the project. 
![image](https://github.com/eratio08/vitest-teamcity-reporter/assets/77048647/30666756-544b-46b6-84c4-396db2fe3d65)
![image](https://github.com/eratio08/vitest-teamcity-reporter/assets/77048647/835bddcc-471c-45a9-af47-a2996151b02d)

**Comment by antoniosZ** [comment]
thank you @a3mitskevich ! it's weird that they don't mention it in their docs
https://vitest.dev/guide/reporters.html
or at least, I could not find it even though yes, I found it now that you pointed it out in their source code...

**Comment by antoniosZ** [comment]
I tried it and it works, thanks again!
